version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}


services:
  django: &django
    
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: hobbify_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "0.0.0.0:5000:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: hobbify_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: hobbify_production_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: hobbify_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: hobbify_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
  nginx:
    container_name: nginx
    restart: always
    build: 
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
