""" Habit group invitations models """

# Django
from django.db import models

# Utils
from hobbify.utils.models import HobbifyModel

# Managers
from hobbify.groups.managers import InvitationManager


class Invitation(HobbifyModel):
    """
    Habit group invitation
    A habit group invitation is a random text that acts as
    a unique code that grants access to a specific group.
    These codes are generated by users that are already
    members of the circle and have a `remaining_invitations`
    value greater than 0.
    """

    code = models.CharField(max_length=20, unique=True)

    issued_by = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        help_text='Habit group member that is providing the invitation',
        related_name='issued_by'
    )

    used_by = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        null=True,
        help_text='User that used the code to enter the group'
    )

    group = models.ForeignKey('groups.Group', on_delete=models.SET_NULL, null=True)

    used = models.BooleanField(default=False)
    used_at = models.DateTimeField(blank=True, null=True)

    # Manager
    objects = InvitationManager()

    def __str__(self):
        """ Return code and group """
        return f'{self.group.slug_name}: #{self.code}'
