# Generated by Django 3.0.8 on 2020-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Set to true when the user has set a private account.', verbose_name='private account'),
        ),
    ]
