# Generated by Django 3.0.8 on 2020-07-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200707_0308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurrentInstance',
        ),
    ]
