# Generated by Django 3.0.8 on 2020-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrentinstance',
            name='recurrence',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='recurrentinstance',
            name='rule',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
