# Generated by Django 3.0.8 on 2020-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrences', '0003_auto_20200707_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentinstance',
            name='recurrence',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recurrentinstance',
            name='rule',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
