name: Continuous Integration and Delivery
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Django
      run: docker build ./compose/production/django/Dockerfile -t hobbify_production_django .

#  deploy:
#    name: Deploy to DigitalOcean
#    runs-on: ubuntu-latest
#    needs: build   
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v1
#      - name: Add environment variables to .env
#        run: |

